/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_me_Hello */

#ifndef _Included_com_me_Hello
#define _Included_com_me_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_me_Hello
 * Method:    say
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_me_Hello_say
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
