/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_me_Hello.h"
#include <iostream>
using namespace std;


JNIEXPORT void JNICALL Java_com_me_Hello_say
  (JNIEnv *, jobject){
    std::cout << "Hello there , let it be , anything can do !" << std::endl;
  }
